name: Release

on:
  push:
    tags:
      - 'release'
  workflow_dispatch:
    inputs:
      release-title:
        description: 'Release title'
        required: true
      release-description:
        description: 'Release description'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'release'
          release_name: 'release'
          draft: false
          prerelease: false
          title: ${{ github.event.inputs.release-title }}
          body: ${{ github.event.inputs.release-description }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ./

      - name: Upload Release Asset excluding .gitignore and .github/workflows
        run: |
          mkdir release
          cp -r ./* release/ --exclude=.gitignore --exclude=.github/workflows
          zip -r release.zip release
          rm -rf release

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: release.zip
          path: release.zip
