name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_title: 
        description: 'Release title'
        required: true

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Create Release Zip
      run: |
        zip -r release.zip . -x .gitignore .github/*
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        commit: release
        tag: release
        name: ${{ github.event.inputs.release_title }}
        draft: false
        prerelease: false
