name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_title: 
        description: 'Release title'
        required: true

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package repository
        run: |
          # Your packaging script here
          # For example, you can use zip to package your repository
          zip -r my-repo.zip .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'release'
          release_name: ${{ github.event.inputs.release_title }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          name: my-repo.zip
          path: my-repo.zip
          upload_url: ${{ steps.create_release.outputs.upload_url }}
