name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_title: 
        description: 'Release title'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.event.inputs.release_title }}
          tag: release
          assets: "release.zip"

      - name: Create Release Zip
        run: |
          zip -r release.zip . -x .gitignore .github/*
